CREATE DATABASE bottle_imaginary;

USE bottle_imaginary;

CREATE TABLE user (
	id_user INT NOT NULL AUTO_INCREMENT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	nama_user VARCHAR(20) NOT NULL
);
CREATE TABLE botol (
	id_botol INT AUTO_INCREMENT PRIMARY KEY,
	id_user INT NOT NULL,
	gambar_botol BLOB NOT NULL,
	merek_botol VARCHAR(10),
	bentuk_botol VARCHAR(10),
	tekstur_botol VARCHAR(10),
	tinggi_botol VARCHAR(10),
	lebar_botol VARCHAR(10),
	waktu TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	FOREIGN KEY (id_user) REFERENCES user(id_user)
);
CREATE TABLE catatan (
	id_catatan INT AUTO_INCREMENT PRIMARY KEY,
	id_botol INT NOT NULL,
	waktu_deteksi TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	lokasi_deteksi VARCHAR(30),
	FOREIGN KEY (id_botol) REFERENCES botol(id_botol)
)
